### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by FezVrasta** [RamonGebben/noBind#1]
I don't understand the purpose of this library. Why don't you just use arrow functions?

example:

``` js
function clickHandler(id, e) {
  console.log(id, e);
}

function MyList(props) {
  const { listItems } = props;
  return listItems.map(item => (
    <button onClick={() => clickHandler(item.id)}>
      Click Me
    </button>
  ))
}
```

**Comment by RamonGebben** [comment]
Because this still creates a new function on each render.
The actual goal of this was to create a function with which you could wrap the `clickHandler` in this example without creating a new function on each rerender.

So sadly I did not succeed yet and your suggestion also does not solve the problem I'm trying to solve but thanks for the feedback. I will keep looking for the right solution.

**Comment by FezVrasta** [comment]
This doesn't make sense at all.

You are already creating a new function every time
https://github.com/RamonGebben/noBind/blob/master/index.js#L10

**Comment by RangerMauve** [comment]
@FezVrasta is correct. This utility will also be creating a new function each time it gets called, and the addition of the conversion of arguments to an array causes a huge performance hit as well. What you might want to do is use "memoization" along with a call to `.bind()` on the function.
